"""Confirm every number on the LS2 report pages is regenerated by a committed script.

ls2 task 15.  Each LS2 page is rebuilt, by the committed script that owns
it, into a scratch docs root.  Then every CSV and the page text are compared
with the committed tree under ``docs/source/reports/``:

========================  ==================================================
page                      regenerated by
========================  ==================================================
``ls2_l23_x{4,2,1}_v1``   ``build_v1.py`` stage 3 (``ls2_ladder.build``)
``ls2_l23_x4_heldout_v1`` the same, ``--config heldout``
``ls2_kd_15pct``          ``kd_15pct.py``
``ls2_kd_l23``            ``train_kd_l23.py`` (full retrain, ~15 min; with
                          ``--quick``, page text only, from its CSVs)
``ls2_refit_ab``          ``refit_ab.py``
``ls2_refit_kappa``       ``refit_kappa.py``
``ls2_ours``              ``ours_report.py``
``ls2_debrief``           ``debrief.py``
``rt_tests_A_l23_v1``     ``rta_rescore_check.py`` (the RT-A page, as task 9b
                          left it)
========================  ==================================================

CSVs are compared cell by cell: strings must match, and numbers must agree to
1e-9 relative (every script is deterministic, so in practice they are
identical).  ``.rst`` text must match exactly.  PNGs are not compared
byte for byte, since matplotlib embeds metadata; each must merely be
regenerated.

Usage, from the repository root::

    PYTHONPATH=. /Users/xavier/miniforge3/envs/ocean14/bin/python \\
        ioptics/runs/prototypes/ls2/verify_reports.py [--quick] [--only NAME ...]

Prints one line per page and exits non-zero if anything differs.
"""

from __future__ import annotations

import importlib.util
import sys
import tempfile
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[3]
COMMITTED = REPO / 'docs' / 'source' / 'reports'


def _load(name):
    spec = importlib.util.spec_from_file_location(f'ls2_{name}', HERE / f'{name}.py')
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _ladder(cfg):
    def run(docs):
        from ioptics import config
        from ioptics.report import ls2_ladder
        b = _load('build_v1')
        b._register()
        sid = config.load(b.CONFIGS[cfg]).sweep_id
        ls2_ladder.build(sid, docs_root=docs, compare_sweep=b.COMPARATOR.get(cfg),
                         compare_algorithm=b.COMPARATOR_ALGORITHM.get(cfg))
        return [sid]
    return run


def _script(name, page, **kw):
    def run(docs):
        _load(name).build(docs, **kw)
        return [page]
    return run


def _kd_l23_quick(docs):
    """Page text from the committed CSVs and weights (no retraining)."""
    import shutil
    src, dst = COMMITTED / 'ls2_kd_l23', docs / 'reports' / 'ls2_kd_l23'
    dst.mkdir(parents=True, exist_ok=True)
    for f in src.glob('*.csv'):
        shutil.copy2(f, dst / f.name)
    _load('train_kd_l23').page_only(docs)
    return ['ls2_kd_l23']


def _rta(docs):
    _load('rta_rescore_check').main(docs)
    return ['rt_tests_A_l23_v1']


PAGES = {
    'x4': _ladder('x4'), 'x2': _ladder('x2'), 'x1': _ladder('x1'),
    'heldout': _ladder('heldout'),
    'kd_15pct': _script('kd_15pct', 'ls2_kd_15pct'),
    'kd_l23': _script('train_kd_l23', 'ls2_kd_l23', save=False),
    'refit_ab': _script('refit_ab', 'ls2_refit_ab', save=False),
    'refit_kappa': _script('refit_kappa', 'ls2_refit_kappa', save=False),
    'ours': _script('ours_report', 'ls2_ours'),
    'debrief': _script('debrief', 'ls2_debrief'),
    'rta': _rta,
}


def compare_csv(a, b, rtol=1e-9):
    """Number of differing cells between two CSVs (shape mismatch = all)."""
    A, B = pd.read_csv(a), pd.read_csv(b)
    if list(A.columns) != list(B.columns) or A.shape != B.shape:
        return max(A.size, B.size, 1)
    bad = 0
    for c in A.columns:
        x, y = A[c], B[c]
        nx, ny = pd.to_numeric(x, errors='coerce'), pd.to_numeric(y, errors='coerce')
        num = nx.notna() | ny.notna()
        same = np.isclose(nx[num], ny[num], rtol=rtol, atol=0, equal_nan=True)
        bad += int((~same).sum())
        bad += int((x[~num].fillna('').astype(str)
                    != y[~num].fillna('').astype(str)).sum())
    return bad


def compare_page(page, scratch):
    """``(n_csv, n_bad_csv_cells, rst_same, missing)`` for one page dir."""
    new, old = scratch / 'reports' / page, COMMITTED / page
    if page == 'rt_tests_A_l23_v1':
        # rta_rescore_check compares its own rebuild against the committed
        # CSVs and reports; the page itself is rt_ladder's
        return None
    csvs = sorted(old.glob('*.csv'))
    bad = sum(compare_csv(f, new / f.name) for f in csvs if (new / f.name).is_file())
    missing = [f.name for f in csvs + sorted(old.glob('*.png')) + sorted(old.glob('*.rst'))
               if not (new / f.name).is_file()]
    rst_same = all((new / f.name).is_file()
                   and (new / f.name).read_text() == f.read_text()
                   for f in old.glob('*.rst'))
    return len(csvs), bad, rst_same, missing


def main(argv=None):
    import argparse
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument('--quick', action='store_true',
                   help='do not retrain the Kd networks (ls2_kd_l23 page text only)')
    p.add_argument('--only', nargs='*', default=None, choices=sorted(PAGES))
    a = p.parse_args(argv)
    warnings.filterwarnings('ignore')
    pages = dict(PAGES)
    if a.quick:
        pages['kd_l23'] = _kd_l23_quick
    scratch = Path(tempfile.mkdtemp(prefix='ls2_verify_'))
    ok = True
    for key in (a.only or pages):
        for page in pages[key](scratch):
            res = compare_page(page, scratch)
            if res is None:
                print(f'{page:28s} see the rta_rescore_check lines above')
                continue
            n, bad, rst_same, missing = res
            good = bad == 0 and rst_same and not missing
            ok &= good
            print(f'{page:28s} {"OK  " if good else "DIFF"} {n} CSVs, '
                  f'{bad} differing cells, page text '
                  f'{"identical" if rst_same else "DIFFERS"}'
                  + (f', missing {missing}' if missing else ''))
    print(f'scratch: {scratch}')
    print('ALL LS2 PAGES REGENERATE' if ok else 'SOME PAGES DIFFER')
    return 0 if ok else 1


if __name__ == '__main__':
    sys.exit(main())
