"""Write ``reports/LS2/ls2_report.md``, the LS2 report (ls2 task 16).

Every number marked **(P)** in the report is read here from the committed
report tables under ``docs/source/reports/`` (themselves regenerated by the LS2
scripts; ``ioptics/runs/prototypes/ls2/verify_reports.py`` checks that).
Numbers marked **(L)** are quoted from a dated log entry in
``claude_prompts/LS2/ls2_execution.md`` and attributed there.  The figures are
copied from the report pages into ``reports/LS2/figures/``, and two summary
figures are drawn here.

Usage, from the repository root::

    /Users/xavier/miniforge3/envs/ocean14/bin/python reports/scripts/ls2_report.py

No data access needed: it reads only committed files.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[2]
DOCS = REPO / 'docs' / 'source' / 'reports'
OUT = REPO / 'reports' / 'LS2'
FIG = OUT / 'figures'

#: (source page dir, file, name in reports/LS2/figures)
COPY = (
    ('ls2_l23_x4_v1', 'ls2_nan_reasons_ls2_i.png', 'fig_nan_reasons_published.png'),
    ('ls2_kd_15pct', 'kd15_ratio_spectrum.png', 'fig_kd15_ratio_spectrum.png'),
    ('ls2_kd_l23', 'kdl23_heldout.png', 'fig_kdl23_heldout.png'),
    ('ls2_kd_l23', 'kdl23_pangaea.png', 'fig_kdl23_pangaea.png'),
    ('ls2_refit_ab', 'refit_spectral.png', 'fig_refit_spectral.png'),
    ('ls2_refit_kappa', 'kappa_fit.png', 'fig_kappa_fit.png'),
    ('ls2_refit_kappa', 'kappa_nan.png', 'fig_kappa_nan.png'),
    ('ls2_l23_x4_heldout_v1', 'ls2_accuracy_vs_wavelength.png',
     'fig_heldout_accuracy_vs_wavelength.png'),
)


def T(page, name, **kw):
    return pd.read_csv(DOCS / page / name, **kw)


def pu(v, d=1):
    return f'{100 * float(v):.{d}f}%'


def pc(v, d=1):
    return f'{100 * float(v):+.{d}f}%'


def pr(v, d=1):
    """A median ratio as a signed percentage."""
    return f'{100 * (float(v) - 1):+.{d}f}%'


# --------------------------------------------------------------------------- #
# summary figures
# --------------------------------------------------------------------------- #

def cell_mae(cell):
    """The mae from a comparator cell written as ``'mae 0.846, bias -0.376'``."""
    return float(str(cell).split(',')[0].split()[1])


def _plt():
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    return plt


def fig_headline(head, path):
    plt = _plt()
    order = ['published', 'published at effective μw', 'refit a/bb + published κ',
             'our LS2 (refit a/bb + κ)']
    colors = ['C3', 'C1', '0.6', 'k']
    comps = [('a_median_err', 'a'), ('bb_median_err', 'bb'), ('bb_p_median_err', 'bb_p')]
    fig, axes = plt.subplots(1, 3, figsize=(11, 3.4), sharey=False)
    for ax, th in zip(axes, (0, 30, 60)):
        h = head[head.theta_s == th].set_index('tables')
        x = np.arange(len(comps))
        w = 0.2
        for i, (t, c) in enumerate(zip(order, colors)):
            ax.bar(x + (i - 1.5) * w, [100 * h.loc[t, col] for col, _ in comps], w,
                   color=c, label=t)
        ax.axhline(0, color='k', lw=0.6)
        ax.set_xticks(x, [lab for _, lab in comps])
        ax.set_title(f'θs = {th}°', fontsize=10)
    axes[0].set_ylabel('median relative error [%]')
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, fontsize=8, loc='lower center', ncol=4,
               frameon=False)
    fig.suptitle('Rung (i): true inputs, noise-free L23 X=4, held-out scenarios',
                 fontsize=10)
    fig.tight_layout(rect=(0, 0.08, 1, 1))
    fig.savefig(path, dpi=130)
    plt.close(fig)


def fig_vs_bing(vb, path):
    plt = _plt()
    rungs = [('ls2_iii', 'published LS2,\noperational'),
             ('ls2r_iii_l23', 'our LS2,\noperational'),
             ('ls2r_i', 'our LS2,\ntrue inputs')]
    cells = [('a', '440 nm'), ('a_nw', '440 nm'), ('bb', '555 nm'), ('bb_p', '555 nm')]
    V = vb.set_index(['rung', 'component', 'scope'])
    fig, axes = plt.subplots(1, 4, figsize=(12, 3.4))
    for ax, (comp, scope) in zip(axes, cells):
        ls2 = [100 * V.loc[(r, comp, scope), 'mae_ls2'] for r, _ in rungs]
        bing = [100 * V.loc[(r, comp, scope), 'mae_bing'] for r, _ in rungs]
        x = np.arange(len(rungs))
        ax.bar(x - 0.18, ls2, 0.36, color='k', label='LS2')
        ax.bar(x + 0.18, bing, 0.36, color='C0', label='MCMC BING (same spectra)')
        ax.set_xticks(x, [lab for _, lab in rungs], fontsize=7)
        ax.set_title(f'{comp}({scope.split()[0]})', fontsize=10)
    axes[0].set_ylabel('mae [%]')
    axes[0].legend(fontsize=7)
    fig.suptitle('LS2 against MCMC BING, held-out L23 X=4, paired by spectrum',
                 fontsize=10)
    fig.tight_layout()
    fig.savefig(path, dpi=130)
    plt.close(fig)


# --------------------------------------------------------------------------- #
# the report
# --------------------------------------------------------------------------- #

def build():
    FIG.mkdir(parents=True, exist_ok=True)
    for page, src, dst in COPY:
        shutil.copy2(DOCS / page / src, FIG / dst)

    lad4 = T('ls2_l23_x4_v1', 'ls2_ladder_all.csv').set_index('rung')
    kdn = T('ls2_l23_x4_v1', 'kd_noise_all.csv')
    head = T('ls2_ours', 'ours_headline.csv')
    vb = T('ls2_ours', 'ours_vs_bing_heldout.csv')
    held = T('ls2_ours', 'ours_heldout_ladder.csv').set_index('rung')
    sc = T('ls2_debrief', 'debrief_side_chains.csv')
    k15 = T('ls2_kd_15pct', 'kd15_bands.csv').set_index('network')
    kdh = T('ls2_kd_l23', 'kdl23_heldout.csv').set_index(['condition', 'predictor'])
    kdp = T('ls2_kd_l23', 'kdl23_pangaea.csv')
    kdg = T('ls2_kd_l23', 'kdl23_geometry_summary.csv').set_index(
        ['network', 'geometry_input'])
    kda = T('ls2_kd_l23', 'kdl23_ablation.csv').set_index(['network', 'trained_on'])
    rs = T('ls2_refit_ab', 'refit_scores.csv').set_index(['version', 'component'])
    rl = T('ls2_refit_ab', 'refit_limiting.csv').set_index('theta_s')
    rd = T('ls2_refit_ab', 'refit_domain.csv').set_index('quantity')
    ki = T('ls2_refit_kappa', 'kappa_inversions.csv').set_index(['set', 'config'])
    kt = T('ls2_refit_kappa', 'kappa_vs_truth.csv').set_index('kappa_table')

    fig_headline(head, FIG / 'fig_headline_rung_i.png')
    fig_vs_bing(vb, FIG / 'fig_ls2_vs_bing.png')

    text = _text(lad4, kdn, head, vb, held, sc, k15, kdh, kdp, kdg, kda, rs, rl,
                 rd, ki, kt)
    (OUT / 'ls2_report.md').write_text(text, encoding='utf-8')
    print(f'wrote {OUT / "ls2_report.md"} and {len(COPY) + 2} figures')


def _text(lad4, kdn, head, vb, held, sc, k15, kdh, kdp, kdg, kda, rs, rl, rd, ki, kt):
    H = head.set_index(['theta_s', 'tables'])
    hp, he = H.loc[(0, 'published')], H.loc[(0, 'published at effective μw')]
    hab, ho = H.loc[(0, 'refit a/bb + published κ')], H.loc[(0, 'our LS2 (refit a/bb + κ)')]
    V = vb.set_index(['rung', 'component', 'scope'])
    v = lambda r, c, s: V.loc[(r, c, s)]                       # noqa: E731
    S = sc.set_index(['side_chain', 'tables'])
    slope = kdn[kdn.rung.str.startswith('slope')].iloc[0]
    n = lambda c, p: kdh.loc[(c, p)]                           # noqa: E731
    pg = kdp.set_index(['tol_nm', 'predictor', 'subset'])
    g = lambda *k: pg.loc[k]                                   # noqa: E731
    bing = lad4.loc['BING']
    return f"""\
# LS2 in IOPtics: what was built, what was measured, and what it means

*Report on the LS2 work specified and logged in
`claude_prompts/LS2/ls2_execution.md` (tasks 1–15, plus 9a/9b; 15a, the
leaderboard fold, runs on the workstation).  Written 2026-10-04 by Claude
(Opus 5.5) for J. Xavier Prochaska.  Every number is either **(P)**, read by
`reports/scripts/ls2_report.py` from a committed report table under
`docs/source/reports/` (each regenerated by its committed script, which
`verify_reports.py` checks), or **(L)**, quoted from a dated log entry in
`ls2_execution.md`.  Nothing is quoted from memory.  "mae" in the IOPtics
tables is the fractional multiplicative error 10^mean|log10(ret/true)| − 1;
the Kd-network section uses mean|ln(ret/true)| and says so.*

---

## 1. Summary

LS2 (Loisel et al. 2018) inverts remote-sensing reflectance and the diffuse
attenuation coefficient ⟨Kd⟩₁ into total absorption `a` and backscattering
`bb` through published polynomial look-up tables.  It was brought into IOPtics
as its first **direct** algorithm (no fit, no likelihood, totals only).  It
was benchmarked on the L23 Hydrolight corpus as a ladder of inputs, set
against MCMC BING, then rebuilt from L23 to see how much of its error was
avoidable.

* **Published LS2 carries three avoidable errors on L23.**
  - An illumination convention (Snell's μw) that L23's diffuse sky does not
    follow is worth the whole `a` bias: {pc(hp['a_median_err'])} at θs = 0°
    with true inputs, {pc(he['a_median_err'])} once the published tables are
    entered at L23's effective μw **(P)**.
  - Its Raman table κ is unavailable on {pu(hp['kappa_unavailable'])} of
    cells **(P)**: a broken 502 nm row, a stop at 702 nm, and ranges narrower
    than L23.
  - The MODIS Kd network ocpy shipped (v1.1) swings
    {pr(k15.loc['MODIS_v1.1', 'vis_min'], 0)} to
    {pr(k15.loc['MODIS_v1.1', 'vis_max'], 0)} with wavelength against L23
    **(P)**.
* **Rebuilding the three pieces from L23 removes most of it.**  At θs = 0°,
  true inputs, held-out scenarios: `a` {pc(hp['a_median_err'])} →
  {pc(ho['a_median_err'])}, `bb` {pc(hp['bb_median_err'])} →
  {pc(ho['bb_median_err'])}, `bb_p` {pc(hp['bb_p_median_err'])} →
  {pc(ho['bb_p_median_err'])}; κ unavailable {pu(hp['kappa_unavailable'])} →
  {pu(ho['kappa_unavailable'], 2)} **(P)**.
* **Operationally the Kd network dominates.**  Rung (iii) `a(440)` mae goes
  from {pu(held.loc['ls2_iii', 'a_440_mae'])} (published) to
  {pu(held.loc['ls2r_iii', 'a_440_mae'])} (our tables, the same network) to
  {pu(held.loc['ls2r_iii_l23', 'a_440_mae'])} (our tables and our L23 Kd
  network) **(P)**.
* **Against MCMC BING the trade is one-sided per component.**  On absorption
  totals LS2 is competitive or better: `a(440)` {pu(v('ls2r_iii_l23', 'a', '440 nm')['mae_ls2'])}
  vs {pu(v('ls2r_iii_l23', 'a', '440 nm')['mae_bing'])} operationally,
  {pu(v('ls2r_i', 'a', '440 nm')['mae_ls2'])} vs {pu(v('ls2r_i', 'a', '440 nm')['mae_bing'])}
  with true inputs.  On backscattering BING wins clearly: `bb(555)`
  {pu(v('ls2r_i', 'bb', '555 nm')['mae_bing'])} vs
  {pu(v('ls2r_i', 'bb', '555 nm')['mae_ls2'])}, because LS2 inverts band by
  band and inherits each band's noise.  LS2 has no `a_ph`/`a_dg`; BING's are
  poor (`a_ph(440)` mae {pu(cell_mae(bing['a_ph_440']))}) **(P)**.
* **Everything is L23.**  Our Kd network reads low against real PANGAEA water
  (median ratio {g(2.5, 'L23 seawifs (mlp)', 'in scope')['median_ratio']}
  in scope) **(P)**.  Only the published operational LS2 goes on the
  leaderboard (Q41).

![](figures/fig_headline_rung_i.png)

*Figure 1.  Rung (i) median relative error on held-out L23 X=4, noise-free,
for four table configurations (P; table `ls2_ours/ours_headline.csv`).  At
θs = 60°, where the published tables were already close (`bb`
{pc(H.loc[(60, 'published'), 'bb_median_err'])}, `bb_p`
{pc(H.loc[(60, 'published'), 'bb_p_median_err'])}), ours over-correct slightly
(`bb` {pc(H.loc[(60, 'our LS2 (refit a/bb + κ)'), 'bb_median_err'])}, `bb_p`
{pc(H.loc[(60, 'our LS2 (refit a/bb + κ)'), 'bb_p_median_err'])}).*

---

## 2. What LS2 is, and how it was set up

LS2 computes `a = ⟨Kd⟩₁ / P₃(Rrs)` and `bb = ⟨Kd⟩₁ · (d₀Rrs + d₁Rrs² +
d₂Rrs³)`.  The coefficients are tabulated on 21 values of η = b_w/b and 8 of
μw, the cosine of the refracted solar beam.  A Raman correction κ(bb/a) is
iterated.  It needs ⟨Kd⟩₁ and the particulate scattering b_p as inputs, so
IOPtics runs it as a **ladder** whose rungs differ in one input each:

| rung | Kd | b_p | role |
|---|---|---|---|
| (i) `ls2_i` | true ⟨Kd⟩₁ | true | LS2 alone |
| (ii) `ls2_ii` | true | OC4v4 Chl → `bp_from_chla` | + the Chl side chain |
| (iii) `ls2_iii` | authors' PACE v2.3 network | OC4v4 | operational (satellite mode) |
| `ls2_iii_modis` | authors' MODIS v1.3 network | OC4v4 | second Kd network |
| `ls2_i_effmuw` | true | true | tables at L23's effective μw (diagnostic) |
| `ls2_i_kdnoise05/10/20` | true × (1 + σε), one draw per spectrum | true | Kd-error sensitivity |

Data: L23 (Loisel et al. 2023), 3,320 IOP scenarios at θs = 0/30/60°, in
three realizations: X=1 elastic, X=2 + Raman, X=4 + Raman + Chl
fluorescence.  Rrs carries PACE-form noise (the same form as the BING
benchmark RT-A, not the same draws), and the window is 400–750 nm.  The BING
comparator is RT-A's MCMC `expb_pow_hyb_ramfl`, the RT rung whose physics
matches X=4 (Q36).

---

## 3. What was built

**Upstream, ocpy.**
- `ls2_invert`: vectorized (800k cells in 0.34 s single-pass, 1.5 s iterated,
  down from 18.5 min for the scalar path) **(L, 2026-09-26)**.  It iterates
  the Raman correction to convergence, flags every NaN per cell, and has
  three corrected porting defects.  It matches the authors' reference vector
  to 1e-9 **(L)**.
- The Chl side chain: `oc4v4` and `bp_from_chla`.  The 0.347·Chl^0.766
  amplitude was traced to Loisel & Morel 1998 Eq. 6, which is a regression on
  c_p, not b_p **(L, 2026-10-02)**.
- The authors' Kd networks: MODIS v1.1, v1.3 and PACE v2.3, matching their
  reference vectors to ≤1.8e-13 **(L, 2026-10-03)**.  The `Kd_NN_MODIS`
  default now points at v1.3.
- A fixed ZHH2009 pure-water scattering.  It had three transcription errors,
  one of them a 25% error pinned by its own test, and now matches L23 to
  −0.27% **(L, 2026-10-03)**.
- `kd_l23`: our L23-trained Kd networks, NumPy-only inference.
- `refit`: the smooth a/bb refit and κ refit.
- Two re-derived tables: `LS2_LUT_L23_v1.npz` (a/bb) and
  `LS2_LUT_L23_abk_v1.npz` (a/bb + κ).

**IOPtics.**
- `DirectSpec`, a second spec type, with an honest `fit_method='direct'`,
  and a `pool` column so direct rows meet each fitted population in contests.
- Per-cell NaN reasons.
- Explicit "not applicable" rows for components an algorithm cannot produce.
- ⟨Kd⟩₁ from L23's profile files, with three definitions.  L23's stored z₁
  disagrees with its own Ed profile by up to 1.77× at 700 nm, but the
  definitions agree to ≤0.03% in median **(L, 2026-10-03)**.
- The LS2 driver and ladder registry; the `ls2_ladder` report page; the
  Flax/Optax Kd-network trainer `kd_net`.
- Sweeps on X=1/2/4, a held-out sweep, and a leaderboard sweep.
- Ten report page directories (four ladder pages, plus the Kd diagnostic,
  the Kd networks, the a/bb refit, the κ refit, "our own LS2" and the
  debrief), and `verify_reports.py`, which rebuilds every LS2 page from its
  committed script and compares it cell by cell.  On the final run
  all 10 pages regenerated with 0 differing cells **(L, 2026-10-04,
  task 15)**.

**Fixes made along the way.**
- A bootstrap seed that hashed `repr(np.float64)`: a numpy-2 type change had
  silently redrawn every published interval.  It was fixed, and RT-A's
  published head-to-heads now reproduce exactly **(L, Q37)**.
- A leaderboard ranking bug that dropped pre-`pool` rows from every contest
  **(L, task 15)**.
- RT-A was brought from the workstation (9a/9b), given BING's `a_nw`, and
  re-scored.  All its published numbers reproduce **(L, 9b)**.

---

## 4. Results

### 4.1 The published ladder on L23 X=4 (all 3,320 spectra, noisy Rrs)

| rung | `a(440)` mae | `bb(555)` mae | `bb(555)` median | `bb_p(555)` median |
|---|---|---|---|---|
| (i) true inputs | {pu(lad4.loc['ls2_i', 'a_440_mae'])} | {pu(lad4.loc['ls2_i', 'bb_555_mae'])} | {pr(lad4.loc['ls2_i', 'bb_555_ratio'])} | {pr(lad4.loc['ls2_i', 'bb_p_555_ratio'])} |
| (ii) + OC4v4 b_p | {pu(lad4.loc['ls2_ii', 'a_440_mae'])} | {pu(lad4.loc['ls2_ii', 'bb_555_mae'])} | {pr(lad4.loc['ls2_ii', 'bb_555_ratio'])} | {pr(lad4.loc['ls2_ii', 'bb_p_555_ratio'])} |
| (iii) PACE Kd network | {pu(lad4.loc['ls2_iii', 'a_440_mae'])} | {pu(lad4.loc['ls2_iii', 'bb_555_mae'])} | {pr(lad4.loc['ls2_iii', 'bb_555_ratio'])} | {pr(lad4.loc['ls2_iii', 'bb_p_555_ratio'])} |
| (iii) MODIS v1.3 Kd | {pu(lad4.loc['ls2_iii_modis', 'a_440_mae'])} | {pu(lad4.loc['ls2_iii_modis', 'bb_555_mae'])} | {pr(lad4.loc['ls2_iii_modis', 'bb_555_ratio'])} | {pr(lad4.loc['ls2_iii_modis', 'bb_p_555_ratio'])} |
| effective μw | {pu(lad4.loc['ls2_i_effmuw', 'a_440_mae'])} | {pu(lad4.loc['ls2_i_effmuw', 'bb_555_mae'])} | {pr(lad4.loc['ls2_i_effmuw', 'bb_555_ratio'])} | {pr(lad4.loc['ls2_i_effmuw', 'bb_p_555_ratio'])} |
| MCMC BING (RT-A) | {pu(bing['a_440_mae'])} | {pu(bing['bb_555_mae'])} | {pr(bing['bb_555_ratio'])} | {pr(bing['bb_p_555_ratio'])} |

*(P; `ls2_l23_x4_v1/ls2_ladder_all.csv`.)*

**Kd error costs `a` almost one-for-one.**  On the Kd-noise rungs, `a(440)`
mae rises by {float(slope['a_440_mae']):.2f} per unit of relative Kd error
(one multiplicative draw per spectrum) **(P)**.  Strict `ok` (every output
finite and positive at every band) is rare under noise, because PACE noise
drives red Rrs negative.  Spectra are therefore scored cell by cell (Q31).
The PACE network fails outright on 118 X=4 records, whose red Rrs are
negative **(L, task 8)**.

![](figures/fig_nan_reasons_published.png)

*Figure 2.  Where published LS2 (rung i, X=4) returns nothing, per
wavelength and reason.  The κ hole at 490–505 nm and the stop at 702 nm are
the table's.*

### 4.2 The 15% question: is L23's ⟨Kd⟩₁ the truth, or the network? (task 10)

Planning found the shipped MODIS network 15–18% high at 440/490 nm against
L23.  It reproduces: {pr(k15.loc['MODIS_v1.1', '440'], 0)} at 440 and
{pr(k15.loc['MODIS_v1.1', '490'], 0)} at 490 nm.  But it is a
wavelength sawtooth, not a blue offset: {pr(k15.loc['MODIS_v1.1', '520'], 0)}
at 520, {pr(k15.loc['MODIS_v1.1', '580'], 0)} at 580 and
{pr(k15.loc['MODIS_v1.1', '600'], 0)} at 600 nm.  The authors' PACE v2.3
network agrees with L23 to a median {pu(k15.loc['PACE_v2.3', 'vis_mad'])} over
400–700 nm **(P)**.  The ⟨Kd⟩₁ definition, pure water and band interpolation
were each ruled out, on size and on structure (the error scales with Kd).
**Verdict: L23 is the truth to train against; the v1.1 network is wrong.**

![](figures/fig_kd15_ratio_spectrum.png)

*Figure 3.  Network Kd / L23 ⟨Kd⟩₁ against wavelength (L23 X=4, θs = 0°).*

### 4.3 Our own Kd networks (task 11)

Two tanh MLPs, trained on L23 X=4 (Q38) with PACE-noise augmentation and
split by IOP scenario:
- a hyperspectral one, 71 bands from 400 to 750 nm;
- a five-band SeaWiFS-like one.

The target is ln(μw⟨Kd⟩₁), with 1/μw analytic.  A held-out-zenith experiment
rejected μw as an input: with it, the five-band network's error at an unseen
60° was {pu(kdg.loc[('seawifs', True), 'min'])}–{pu(kdg.loc[('seawifs', True), 'max'])}
depending on seed, against {pu(kdg.loc[('seawifs', False), 'median'])} without
it **(P)**.

| held-out L23, PACE noise | mean abs ln ratio, 400–700 nm |
|---|---|
| ours, hyperspectral | {pu(n('noisy', 'L23 hyper (mlp)')['mae_ln_vis'])} |
| ours, five-band | {pu(n('noisy', 'L23 seawifs (mlp)')['mae_ln_vis'])} |
| authors' PACE v2.3 | {pu(n('noisy', 'PACE_v2.3')['mae_ln_vis'])} (fails on {pu(n('noisy', 'PACE_v2.3')['frac_nan'])} of cells) |
| authors' MODIS v1.3 | {pu(n('noisy', 'MODIS_v1.3')['mae_ln_vis'])} |
| authors' MODIS v1.1 (formerly shipped) | {pu(n('noisy', 'MODIS_v1.1')['mae_ln_vis'])} |

*(P; `ls2_kd_l23/kdl23_heldout.csv`.)*  Trained on elastic X=1 instead, the
hyperspectral network scores {pu(kda.loc[('hyper', 'X=1'), 'mae_ln_vis_on_X4'])}
on X=4 **(P)**.  **Off L23 it is a different story.**  On PANGAEA's measured
Kd, the five-band network reads low: median ratio
{g(6.0, 'L23 seawifs (mlp)', 'all matched')['median_ratio']} over
{int(g(6.0, 'L23 seawifs (mlp)', 'all matched')['n_spectra'])} spectra.  On
the {int(g(6.0, 'MODIS_v1.1', 'common and in scope')['n_spectra'])} in-scope
spectra all three can score, MODIS v1.1 is closest
({g(6.0, 'MODIS_v1.1', 'common and in scope')['mae_ln']} against
{g(6.0, 'L23 seawifs (mlp)', 'common and in scope')['mae_ln']} for ours)
**(P)**: the reverse of the L23 ranking.

![](figures/fig_kdl23_heldout.png)

*Figure 4.  Kd networks on held-out L23 X=4 with PACE noise.*

![](figures/fig_kdl23_pangaea.png)

*Figure 5.  Five-band network and the authors' MODIS networks against
PANGAEA's measured Kd (±6 nm band matching).*

### 4.4 Re-deriving the a and bb tables (task 12)

The cubic form is kept.  Each coefficient becomes a quadratic in √η times
(1, 1/μw) for `a` or (1, μw) for `bb`, fitted to L23 X=1 by one weighted
linear least-squares solve: 24 + 18 parameters against the published 672 +
504.  The μw bases were chosen by a leave-one-zenith-out check.  On held-out
L23 X=1 with true inputs (P; `ls2_refit_ab/refit_scores.csv`):

| | published `a` | refit `a` | published `bb` | refit `bb` |
|---|---|---|---|---|
| median | {pr(rs.loc[('published (table)', 'a'), 'median_ratio'], 2)} | {pr(rs.loc[('refit (table)', 'a'), 'median_ratio'], 2)} | {pr(rs.loc[('published (table)', 'bb'), 'median_ratio'], 2)} | {pr(rs.loc[('refit (table)', 'bb'), 'median_ratio'], 2)} |
| mean abs ln ratio | {pu(rs.loc[('published (table)', 'a'), 'mae'])} | {pu(rs.loc[('refit (table)', 'a'), 'mae'])} | {pu(rs.loc[('published (table)', 'bb'), 'mae'])} | {pu(rs.loc[('refit (table)', 'bb'), 'mae'])} |

**The limiting relation, and why `a` was biased.**  The refit's
Rrs → 0 limit c₀ is {rl.loc[0, 'refit_c0_eta0.02']}, {rl.loc[30, 'refit_c0_eta0.02']}
and {rl.loc[60, 'refit_c0_eta0.02']} at 0/30/60°.  That matches L23's
1/μ_eff ({rl.loc[0, 'inv_mu_eff']}, {rl.loc[30, 'inv_mu_eff']},
{rl.loc[60, 'inv_mu_eff']}), not the paper's 1/μw ({rl.loc[0, 'inv_muw']},
{rl.loc[30, 'inv_muw']}, {rl.loc[60, 'inv_muw']}) **(P)**.  L23's b/a reaches
only {rd.loc['b/a', 'L23_max']} against the paper's 30, so turbid water is an
extrapolation.

![](figures/fig_refit_spectral.png)

*Figure 6.  Median retrieved/true per wavelength, published vs refit tables
(held-out L23 X=1, true inputs).*

### 4.5 Re-deriving κ (task 13)

On L23, κ is measured directly: κ = Rrs(X=1)/Rrs(X=2), the same water with
and without Raman.  The refit keeps the published form (a cubic in bb/a per
wavelength) over 350–750 nm, with ranges taken from L23.  In a held-out X=2
inversion with true inputs (P; `ls2_refit_kappa/*.csv`):

| | κ unavailable | `bb` mae | `bb_p` mae |
|---|---|---|---|
| no correction | – | {pu(ki.loc[('X=2', 'refit a/bb without κ'), 'bb_mae'])} | {pu(ki.loc[('X=2', 'refit a/bb without κ'), 'bb_p_mae'])} |
| published κ | {pu(ki.loc[('X=2', 'refit a/bb + published κ'), 'kappa_nan_rate'])} | {pu(ki.loc[('X=2', 'refit a/bb + published κ'), 'bb_mae'])} | {pu(ki.loc[('X=2', 'refit a/bb + published κ'), 'bb_p_mae'])} |
| refit κ | {pu(ki.loc[('X=2', 'refit a/bb + refit κ'), 'kappa_nan_rate'], 2)} | {pu(ki.loc[('X=2', 'refit a/bb + refit κ'), 'bb_mae'])} | {pu(ki.loc[('X=2', 'refit a/bb + refit κ'), 'bb_p_mae'])} |
| elastic ceiling (X=1) | – | {pu(ki.loc[('X=1 (elastic ceiling)', 'refit a/bb without κ'), 'bb_mae'])} | {pu(ki.loc[('X=1 (elastic ceiling)', 'refit a/bb without κ'), 'bb_p_mae'])} |

The published table can evaluate only {pu(kt.loc['published', 'evaluable_500'])}
of cells at 500 nm **(P)**.  κ depends on the sun angle, but not
monotonically: at θs = 0° it sits apart from 30° and 60°, which agree with
each other.  So no μw term survived the leave-one-zenith-out check, and that
dependence is the floor left between the refit and the elastic ceiling.

![](figures/fig_kappa_nan.png)

*Figure 7.  Share of cells with κ unavailable, published vs refit (held-out
X=2 and X=4).*

![](figures/fig_kappa_fit.png)

*Figure 8.  True κ against bb/a, coloured by solar zenith, with both cubics.*

### 4.6 Our own LS2 against the published one, and against BING (task 14)

The re-derived rungs run on the held-out sweep, where none of the re-derived
pieces was fitted.  The L23-network rung runs **only** there (Q39).

| held-out, noisy | `a(440)` mae | `bb(555)` mae | `bb(555)` bias |
|---|---|---|---|
| published, true inputs | {pu(held.loc['ls2_i', 'a_440_mae'])} | {pu(held.loc['ls2_i', 'bb_555_mae'])} | {pc(held.loc['ls2_i', 'bb_555_bias'])} |
| ours, true inputs | {pu(held.loc['ls2r_i', 'a_440_mae'])} | {pu(held.loc['ls2r_i', 'bb_555_mae'])} | {pc(held.loc['ls2r_i', 'bb_555_bias'])} |
| published, operational (PACE Kd) | {pu(held.loc['ls2_iii', 'a_440_mae'])} | {pu(held.loc['ls2_iii', 'bb_555_mae'])} | {pc(held.loc['ls2_iii', 'bb_555_bias'])} |
| ours, operational (our L23 Kd) | {pu(held.loc['ls2r_iii_l23', 'a_440_mae'])} | {pu(held.loc['ls2r_iii_l23', 'bb_555_mae'])} | {pc(held.loc['ls2r_iii_l23', 'bb_555_bias'])} |

*(P; `ls2_ours/ours_heldout_ladder.csv`.)*

![](figures/fig_ls2_vs_bing.png)

*Figure 9.  LS2 against MCMC BING, paired spectrum by spectrum on held-out L23
X=4, at the reference bands (P; `ls2_ours/ours_vs_bing_heldout.csv`).*

![](figures/fig_heldout_accuracy_vs_wavelength.png)

*Figure 10.  mae against wavelength on the held-out sweep, for the main
rungs.  Above 700 nm every rung fed by the authors' Kd networks blows up in
`a`; ours stays flat.*

### 4.7 What the two side chains cost

Measured on the held-out X=4 spectra, as the change in `a(440)` mae when a
true input is replaced (P; `ls2_debrief/debrief_side_chains.csv`):

| side chain | published tables | our tables |
|---|---|---|
| Chl/b_p: OC4v4 → `bp_from_chla` | {S.loc[('Chl/b_p', 'published'), 'a_440_cost_pp']:+.1f} pp | {S.loc[('Chl/b_p', 're-derived'), 'a_440_cost_pp']:+.1f} pp |
| Kd: authors' PACE v2.3 | {S.loc[('Kd (PACE v2.3)', 'published'), 'a_440_cost_pp']:+.1f} pp | {S.loc[('Kd (PACE v2.3)', 're-derived'), 'a_440_cost_pp']:+.1f} pp |
| Kd: authors' MODIS v1.3 | {S.loc[('Kd (MODIS v1.3)', 'published'), 'a_440_cost_pp']:+.1f} pp | – |
| Kd: our L23 network | – | {S.loc[('Kd (our L23 network)', 're-derived'), 'a_440_cost_pp']:+.1f} pp |

The b_p chain is cheap because b_p enters only through η, which picks the
table row.  The Kd chain is the expensive one, and how expensive depends
entirely on the network.

---

## 5. What LS2 shows about totals against decomposition

LS2 returns totals (`a`, `bb`) and their non-water parts (`a_nw`, `bb_p`).
It does not split absorption into phytoplankton and CDM.  BING does, and on
L23 X=4 that split is where BING's error lives: `a_ph(440)` mae
{pu(cell_mae(bing['a_ph_440']))} and `a_dg(440)`
{pu(cell_mae(bing['a_dg_440']))}, against {pu(bing['a_440_mae'])}
for its total `a(440)` **(P)**.  An algorithm that declines to split gives up
those two numbers and their errors.  With a good Kd, it then matches or beats
the fitted model on absorption totals.  On backscattering, a full-spectrum fit
averages noise that a band-by-band inversion cannot.

---

## 6. Decisions taken along the way (Q&A, abridged)

- **Q27/Q30**: the authors' PACE network is rung (iii); MODIS v1.3 is the
  alternative; the `Kd_NN_MODIS` default moved to v1.3 after task 10.
- **Q31**: direct spectra that are not strictly `ok` are scored cell by cell.
- **Q33**: Kd noise is one fully correlated draw per spectrum, at 5/10/20%.
- **Q34**: `a_nw` is masked at a_nw/a ≥ 0.1 in figures.
- **Q35**: RT-A was copied from the workstation via the RoB Drive (9a/9b).
- **Q36**: `expb_pow_hyb_ramfl` is "BING" in comparisons.
- **Q37**: bootstrap seeds are now dtype-independent.
- **Q38**: the Kd networks are trained on X=4.
- **Q39**: L23-trained pieces are scored on held-out scenarios only.
- **Q40**: the intermittent MCMC reproducibility test was investigated
  (time-boxed), then relaxed to `allclose(1e-10)`, with a diagnostic message.
- **Q41**: only the published operational LS2 goes on the leaderboard, on
  elastic L23 beside BING (prompt 15a).

---

## 7. Limitations and open items

- **Everything is L23.**  Our tables and networks are L23-trained and scored
  on held-out L23 scenarios.  The PANGAEA check says real water attenuates
  more than L23 predicts from the same Rrs.
- κ's sun dependence and X=4 Chl fluorescence remain uncorrected.  So does
  the band-by-band noise sensitivity of `bb`/`bb_p`, which is structural.
- Turbid water (b/a > {rd.loc['b/a', 'L23_max']}) and θs > 60° are
  extrapolations of the re-derived tables.
- **Prompt 15a (the leaderboard fold) is pending** on the workstation, whose
  board holds sweeps the laptop's lacks.
- No in-situ validation exists for the hyperspectral Kd network.

---

## 8. Reproducing this report

From the repository root, with the `ocean14` interpreter, `PYTHONPATH=.`, and
L23 and RT-A under `$OS_COLOR`:

```
python ioptics/runs/prototypes/ls2/build_v1.py 1 --n-cores 12   # sweeps
python ioptics/runs/prototypes/ls2/build_v1.py 2                # metrics
python ioptics/runs/prototypes/ls2/build_v1.py 3                # ladder pages
python ioptics/runs/prototypes/ls2/kd_15pct.py                  # task 10
python ioptics/runs/prototypes/ls2/train_kd_l23.py              # task 11 (~15 min)
python ioptics/runs/prototypes/ls2/refit_ab.py                  # task 12
python ioptics/runs/prototypes/ls2/refit_kappa.py               # task 13
python ioptics/runs/prototypes/ls2/ours_report.py               # task 14
python ioptics/runs/prototypes/ls2/debrief.py                   # task 15
python ioptics/runs/prototypes/ls2/verify_reports.py            # check all pages
python reports/scripts/ls2_report.py                            # this report
```
"""


if __name__ == '__main__':
    build()
